[project]
name = "fastapi-boilerplate"
version = "0.1.0"
description = "Fastapi boilerplate"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pydantic-settings>=2.9.1",
    "pydantic>=2.11.4",
]
